config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }
  root "games#index"

  resources :critics
  resources :involved_companies
  resources :games do
    resources :critics

    # /games/:id/add_genre
    post "add_genre", on: :member
    # /games/:id/remove_genre
    delete "remove_genre", on: :member

    # /games/:id/add_platform
    post "add_platform", on: :member
    # /games/:id/remove_platform
    delete "remove_platform", on: :member
  end
  resources :platforms
  resources :genres
  resources :companies do
    resources :critics
  end
  resources :users
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  # GET /platforms
  def index
    @platforms = Platform.all
  end

  # GET /platforms/:id
  def show
    @platform = Platform.find(params[:id])
  end

  # GET /platforms/new
  def new
    @platform = Platform.new
  end

  # GET /platforms/:id/edit
  def edit
    @platform = Platform.find(params[:id])
  end

  # POST /platforms
  def create
    @platform = Platform.new(platform_params)

    if @platform.save
      redirect_to @platform
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /platforms/:id
  def update
    @platform = Platform.find(params[:id])

    if @platform.update(platform_params)
      redirect_to @platform
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /platforms/:id
  def destroy
    @platform = Platform.find(params[:id])
    @platform.destroy
    redirect_to platforms_url, status: :see_other
  end

  private

  # Only allow a list of trusted parameters through.
  def platform_params
    params.require(:platform).permit(:name, :category)
  end
end

app/views/platforms/_form.html.erb
<%= form_with(model: platform, class: "flex flex-column gap-4") do |form| %>
  <div class="flex gap-4 mb-2">
    <div class="input">
      <%= form.label :name, class:"content-xs overline"%>
      <div class="input__container">
        <%= form.text_field :name, class: "input__content", placeholder: "Super Play Station XP" %>
      </div>
      <% if platform.errors.messages[:name].any? %>
      <span class="content-sm input__error-message">
        <%= platform.errors.messages[:name].join(", ")%>
      </span>
      <% end %>
    </div>
  </div>

  <div class="flex gap-4 mb-2">
    <div class="select">
      <%= form.label :category, class:"content-xs overline"%>
      <%= form.select :category, Platform.categories.keys, { prompt: true }, { class: "select__input" } %>
      <% if platform.errors.messages[:category].any? %>
      <span class="content-sm input__error-message">
        <%= platform.errors.messages[:category].join(", ")%>
      </span>
      <% end %>
    </div>
  </div>

  <%= form.submit class: "button button--primary fit-content" %>

<% end %>

app/views/platforms/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">Editing Platform</h1>

    <%= render 'form', platform: @platform %>

    <%= link_to 'Back', platforms_path %>
  </div>
</section>

app/views/platforms/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">Platforms</h1>
    <%= link_to 'New platform', new_platform_path, class: "button button--primary fit-content" %>

    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="colgroup" colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @platforms.each do |platform| %>
            <tr>
              <td><%= platform.name %></td>
              <td><%= platform.category %></td>
              <td><%= link_to 'Show', platform %></td>
              <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
              <td><%= link_to 'Destroy', platform, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/platforms/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">New Platform</h1>

    <%= render 'form', platform: @platform %>

    <%= link_to 'Back', platforms_path %>
  </div>
</section>

app/views/platforms/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">Platform details</h1>
    <div class="flex flex-column gap-4 content-lg">
      <div>
        <strong>Name:</strong>
        <%= @platform.name %>
      </div>
      <div>
        <strong>Category:</strong>
        <%= @platform.category %>
      </div>
      <div>
        <%= link_to 'Edit', edit_platform_path(@platform) %> |
        <%= link_to 'Back', platforms_path %>
      </div>
    </div>
  </div>
</section>