config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }
  root "games#index"

  resources :critics
  resources :involved_companies
  resources :games do
    resources :critics

    # /games/:id/add_genre
    post "add_genre", on: :member
    # /games/:id/remove_genre
    delete "remove_genre", on: :member

    # /games/:id/add_platform
    post "add_platform", on: :member
    # /games/:id/remove_platform
    delete "remove_platform", on: :member
  end
  resources :platforms
  resources :genres
  resources :companies do
    resources :critics
  end
  resources :users
end

app/models/game.rb
class Game < ApplicationRecord
  # Validations
  validates :name, :category, presence: true
  validates :name, uniqueness: true
  validates :rating,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 },
            allow_nil: true
  # Validates parent is included in the list of main_game's only if the category is not main_game
  validates :parent, inclusion: { in: proc { Game.main_game },
                                  message: "is not a valid game" },
                     unless: proc { main_game? || category.nil? }
  # Validates that parent is nil when the game is a main_game
  validates :parent, absence: true, if: proc { main_game? }

  # Enums
  enum category: { main_game: 0, expansion: 1 }

  # Associations
  belongs_to :parent, class_name: "Game", optional: true
  has_many :expansions, class_name: "Game",
                        foreign_key: "parent_id",
                        dependent: :nullify,
                        inverse_of: "parent"

  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies

  has_and_belongs_to_many :genres
  has_and_belongs_to_many :platforms

  has_many :critics, as: :criticable, dependent: :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/:id
  def show
    @game = Game.find(params[:id])
  end

  # GET /games/new
  def new
    @game = Game.new
    @main_games = Game.main_game
  end

  # GET /games/:id/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /games/:id
  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to @game
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /games/:id
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path, status: :see_other
  end

  # Custom Routes

  # POST /games/:id/add_genre
  def add_genre
    game = Game.find(params[:id])
    genre = Genre.find(params[:genre_id])

    game.genres << genre
    redirect_to game
  end

  # DELETE /games/:id/remove_genre
  def remove_genre
    game = Game.find(params[:id])
    genre = Genre.find(params[:genre_id])

    game.genres.delete(genre)
    redirect_to game, status: :see_other
  end

  # POST /games/:id/add_platform
  def add_platform
    game = Game.find(params[:id])
    platform = Platform.find(params[:platform_id])

    game.platforms << platform
    redirect_to game
  end

  # DELETE /games/:id/remove_platform
  def remove_platform
    game = Game.find(params[:id])
    platform = Platform.find(params[:platform_id])

    game.platforms.delete(platform)
    redirect_to game, status: :see_other
  end

  private

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :parent_id)
  end
end

app/views/games/_form.html.erb
<%= form_with(model: game, class: "flex flex-column gap-4") do |form| %>
  <div class="input">
    <%= form.label :name, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.text_field :name, class: "input__content", placeholder: "Magic Game" %>
    </div>
    <%=errors_for(game, :name)%>
  </div>

  <div class="input">
    <%= form.label :summary, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.text_area :summary, class: "input__content", placeholder: "About game SA..." %>
    </div>
    <%=errors_for(game, :summary)%>
  </div>

  <div class="input">
    <%= form.label :release_date, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.date_field :release_date, class: "input__content" %>
    </div>
    <%=errors_for(game, :release_date)%>
  </div>

  <div class="input">
    <%= form.label :rating, class:"content-xs overline"%>
    <div class="input__container">
      <%= form.number_field :rating, step: 0.1, class: "input__content" %>
    </div>
    <%=errors_for(game, :rating)%>
  </div>

  <div class="select">
    <%= form.label :category, class:"content-xs overline"%>
    <%= form.select :category, Game.categories.keys, { prompt: true }, { class: "select__input" } %>
    <%=errors_for(game, :category)%>
  </div>

  <div class="select">
    <%= form.label :parent_id, class:"content-xs overline"%>
    <%= form.collection_select :parent_id, Game.main_game, :id, :name, { include_blank: "Please select" }, { class: "select__input" } %>
    <%=errors_for(game, :parent_id)%>
  </div>

  <%= form.submit class: "button button--primary fit-content" %>

<% end %>

app/views/games/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">Editing Game</h1>

    <%= render 'form', game: @game %>

    <%= link_to 'Show', @game %> |
    <%= link_to 'Back', games_path %>
  </div>
</section>

app/views/games/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">Games</h1>
    <%= link_to 'New game', new_game_path, class: "button button--primary fit-content" %>

    <div class="table-container">
    <table>
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Category</th>
          <th scope="colgroup" colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @games.each do |game| %>
          <tr>
            <td><%= game.name %></td>
            <td><%= game.category %></td>
            <td><%= link_to 'Show', game %></td>
            <td><%= link_to 'Edit', edit_game_path(game) %></td>
            <td><%= link_to 'Destroy', game, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</section>

app/views/games/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">New Game</h1>

    <%= render 'form', game: @game %>

    <%= link_to 'Back', games_path %>
  </div>
</section>

app/views/games/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">Game details</h1>
    <div class="flex flex-column gap-4 content-lg">
      <div>
        <strong>Name:</strong>
        <%= @game.name %>
      </div>

      <div>
        <strong>Summary:</strong>
        <%= @game.summary %>
      </div>

      <div>
        <strong>Release date:</strong>
        <%= @game.release_date %>
      </div>

      <div>
        <strong>Rating:</strong>
        <%= @game.rating %>
      </div>

      <div>
        <strong>Category:</strong>
        <%= @game.category %>
      </div>

      <div>
        <strong>Parent:</strong>
        <%= @game.parent&.name  %>
      </div>

      <div>
        <strong>Genres:</strong>
        <ul>
          <% @game.genres.each do |genre| %>
          <li><%= genre.name%> | <%= link_to 'remove', remove_genre_game_path(@game, genre_id: genre.id), data: { turbo_method: :delete }  %></li>
          <% end %>
          <li>
            <%= form_with(url: add_genre_game_path(@game), class: "flex flex-column gap-4 flex-row") do |form| %>
              <div class="flex gap-4">
                <div class="select">
                  <%= form.collection_select :genre_id, (Genre.all - @game.genres), :id, :name, { prompt: true }, { class: "select__input" } %>
                </div>
              </div>
              <%= form.submit "Add genre", class: "button button--primary fit-content" %>
            <% end %>
          </li>
        </ul>
      </div>

      <div>
        <strong>Platforms:</strong>
        <ul>
          <% @game.platforms.each do |platform| %>
          <li><%= platform.name%> | <%= link_to 'remove', remove_platform_game_path(@game, platform_id: platform.id), data: { turbo_method: :delete }  %></li>
          <% end %>
          <li>
            <%= form_with(url: add_platform_game_path(@game), class: "flex flex-column gap-4 flex-row") do |form| %>
              <div class="flex gap-4">
                <div class="select">
                  <%= form.collection_select :platform_id, (Platform.all - @game.platforms), :id, :name, { prompt: true }, { class: "select__input" } %>
                </div>
              </div>
              <%= form.submit "Add platform", class: "button button--primary fit-content" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div>
        <%= link_to 'Edit', edit_game_path(@game) %> |
        <%= link_to 'Back', games_path %>
      </div>
    </div>
  </div>
</section>