config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }
  root "games#index"

  resources :critics
  resources :involved_companies
  resources :games do
    resources :critics

    # /games/:id/add_genre
    post "add_genre", on: :member
    # /games/:id/remove_genre
    delete "remove_genre", on: :member

    # /games/:id/add_platform
    post "add_platform", on: :member
    # /games/:id/remove_platform
    delete "remove_platform", on: :member
  end
  resources :platforms
  resources :genres
  resources :companies do
    resources :critics
  end
  resources :users
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  # Associations
  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies, counter_cache: true
  has_many :critics, as: :criticable, dependent: :destroy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/:id
  def show
    @company = Company.find(params[:id])
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/:id/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /companies/:id
  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /companies/:id
  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_path, status: :see_other
  end

  private

  # Only allow a list of trusted parameters through.
  def company_params
    params.require(:company).permit(:name, :description, :start_date, :country)
  end
end

app/views/companies/_form.html.erb
<%= form_with(model: company, class: "flex flex-column gap-4") do |form| %>
  <div class="flex gap-4 mb-2">
    <div class="input">
      <%= form.label :name, class:"content-xs overline"%>
      <div class="input__container">
        <%= form.text_field :name, class: "input__content", placeholder: "Company SA" %>
      </div>
      <%=errors_for(company, :name)%>
    </div>
  </div>

  <div class="flex gap-4 mb-2">
    <div class="input">
      <%= form.label :description, class:"content-xs overline"%>
      <div class="input__container">
        <%= form.text_area :description, class: "input__content", placeholder: "About Company SA..." %>
      </div>
      <%=errors_for(company, :description)%>
    </div>
  </div>

  <div class="flex gap-4 mb-2">
    <div class="input">
      <%= form.label :start_date, class:"content-xs overline"%>
      <div class="input__container">
        <%= form.date_field :start_date, class: "input__content" %>
      </div>
      <%=errors_for(company, :start_date)%>
    </div>
  </div>

  <div class="flex gap-4 mb-2">
    <div class="input">
      <%= form.label :country, class:"content-xs overline"%>
      <div class="input__container">
        <%= form.text_field :country, class: "input__content", placeholder: "Peru" %>
      </div>
      <%=errors_for(company, :country)%>
    </div>
  </div>

  <%= form.submit class: "button button--primary fit-content" %>

<% end %>

app/views/companies/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">Editing Company</h1>

    <%= render 'form', company: @company %>

    <%= link_to 'Show', @company %> |
    <%= link_to 'Back', companies_path %>
  </div>
</section>

app/views/companies/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">Companies</h1>
    <%= link_to 'New company', new_company_path, class: "button button--primary fit-content" %>

    <div class="table-container">
    <table>
      <thead>
        <tr>
          <th scope="col">name</th>
          <th scope="col">Games count</th>
          <th scope="colgroup" colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.name %></td>
            <td><%= company.games_count %></td>
            <td><%= link_to 'Show', company %></td>
            <td><%= link_to 'Edit', edit_company_path(company) %></td>
            <td><%= link_to 'Destroy', company, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</section>

app/views/companies/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">New Company</h1>

    <%= render 'form', company: @company %>

    <%= link_to 'Back', companies_path %>
  </div>
</section>

app/views/companies/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="heading">Company details</h1>
    <div class="flex flex-column gap-4 content-lg">
      <div>
        <strong>Name:</strong>
        <%= @company.name %>
      </div>

      <div>
        <strong>Description:</strong>
        <%= @company.description %>
      </div>

      <div>
        <strong>Start date:</strong>
        <%= @company.start_date %>
      </div>

      <div>
        <strong>Country:</strong>
        <%= @company.country %>
      </div>

      <div>
        <strong>Games count:</strong>
        <%= @company.games_count %>
      </div>
      <div>
        <%= link_to 'Edit', edit_company_path(@company) %> |
        <%= link_to 'Back', companies_path %>
      </div>
    </div>
  </div>
</section>